### ISSUE TITLE
Sending a DELETE request returns errors.

### ISSUE THREAD

**Issue by Adoria298** [Adoria298/flask-messenger#10]
Replication:
 1. Set up a local instance of flask-messenger.
 2. Spam it.
 3. Visit /delete/all, and check the output of flask-messenger.

Or:

3. Get a specific message id from the output.
4. Visit /delete/+that specific id, then check the output.

If you're successful, it probably won't say any errors in the output, and that message, (or all the messages), should have disappeared.

Tasks
- [X] Fix /delete/all error
- [ ] Fix /delete/specific id error.

**Comment by Adoria298** [comment]
Actually, its a different error depending on whether you're deleting a specific message, or all the messages.

/delete/all error:
```
127.0.0.1 - - [09/Aug/2018 17:27:16] "DELETE /api/messages HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask_restful/representations/json.py", line 24, in output_json
    resp.headers.extend(headers or {})
  File "/home/adoria298/.local/lib/python3.6/site-packages/werkzeug/datastructures.py", line 1082, in extend
    for key, value in iterable:
TypeError: 'int' object is not iterable
```
/delete/specific-id error:
```
127.0.0.1 - - [09/Aug/2018 17:25:28] "DELETE /api/messages HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/adoria298/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/adoria298/code/flask-messenger/app.py", line 85, in delete
    for index, message in enumerate(messages):
UnboundLocalError: local variable 'messages' referenced before assignment
```
As such, I have changed the title.

**Comment by Adoria298** [comment]
/delete/all has been fixed after PR #15, but /delete/specific-id still returns the same error.

**Comment by Adoria298** [comment]
Technically issue #10 has been fixed, as there are no more errors, in either case. However, it appears that /delete/4 deletes the 4th (zero-indexed) message in messages, not the message with id 4 (which appears not to be the same thing. More tests are happening, but this issue is still not closed.

**Comment by Adoria298** [comment]
Commit 140e5a4 saved the day. The final issue was the same as issue #3.
